"""Run POST idempotency keys (safe client retries).

Client-initiated reconciliation runs can be retried after a timeout or
network failure.  Without an idempotency key a retry would create a second
run (and duplicate ledger decisions).  This table maps
(tenant_id, idempotency_key) -> run_id so a retry with the SAME key returns
the original run instead of re-executing.

The key is generated by the CLIENT (frontend retry layer) and only stored;
it is never used for authentication.
"""

revision = "0009"
down_revision = "0008"
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade() -> None:
    op.create_table(
        "reconciliation_run_idempotency",
        sa.Column("id", sa.Integer(), primary_key=True, autoincrement=True),
        sa.Column("tenant_id", sa.String(128), sa.ForeignKey("tenants.tenant_id"), nullable=False),
        sa.Column("idempotency_key", sa.String(128), nullable=False),
        sa.Column("run_id", sa.String(128), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False, server_default=sa.text("NOW()")),
        sa.UniqueConstraint("tenant_id", "idempotency_key", name="uq_run_idem_tenant_key"),
    )
    op.create_index("idx_run_idem_run", "reconciliation_run_idempotency", ["run_id"])


def downgrade() -> None:
    op.drop_table("reconciliation_run_idempotency")
